services:
  showup-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: showup-website
    restart: unless-stopped
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.showup-website.rule=Host(`showup.lifestyle`)"
      - "traefik.http.routers.showup-website.entrypoints=web"
      - "traefik.http.services.showup-website.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy-net"

networks:
  proxy-net:
    external: true

